export const countries = [
  {id: '', name: 'Selecciona un país'},
  {id: 'AR', name: 'Argentina'},
  {id: 'BO', name: 'Bolivia'},
  {id: 'CL', name: 'Chile'},
  {id: 'CO', name: 'Colombia'},
  {id: 'CR', name: 'Costa Rica'},
  {id: 'CU', name: 'Cuba'},
  {id: 'DO', name: 'República Dominicana'},
  {id: 'EC', name: 'Ecuador'},
  {id: 'SV', name: 'El Salvador'},
  {id: 'ES', name: 'España'},
  {id: 'GT', name: 'Guatemala'},
  {id: 'GQ', name: 'Guinea Ecuatorial'},
  {id: 'HN', name: 'Honduras'},
  {id: 'MX', name: 'México'},
  {id: 'NI', name: 'Nicaragua'},
  {id: 'PA', name: 'Panamá'},
  {id: 'PY', name: 'Paraguay'},
  {id: 'PE', name: 'Perú'},
  {id: 'PR', name: 'Puerto Rico'},
  {id: 'UY', name: 'Uruguay'},
  {id: 'VE', name: 'Venezuela'}
]
